generators/app/templates/src/main/webapp/app/admin/entity-audit/_entity-audits.html
Angular Filter doesn't work because of invalid input type
resolution:
change input type to "text" on search by entityId
=> minor input type fix

generators/app/templates/src/main/java/package/web/rest/dto/_AbstractAuditingDTO.java
Replaced @NotNull with @ReadOnlyProperty annotation. Fix #21
=> Replaced @NotNull with @ReadOnlyProperty annotation. Fix #21

generators/app/index.js, generators/app/templates/src/main/java/package/domain/_EntityAuditEvent.java, generators/app/templates/src/main/resources/config/liquibase/changelog/_EntityAuditEvent.xml
* javers updated to latest version 
* javers now supports sql databases too
close #19
=> Javers updates

README.md, generators/app/index.js, generators/app/templates/src/main/java/package/domain/_EntityAuditEvent.java, generators/app/templates/src/main/resources/config/liquibase/changelog/_EntityAuditEvent.xml
I didn't think about it yesterday, but the while jpa stuff is not required when using javers and sql
=> remove not required jpa annotations when using javers

generators/app/templates/src/main/java/package/web/rest/_EntityAuditResource.java
=> add transactional annotation to fix lob loading in pgsql.

generators/app/index.js, generators/app/templates/src/main/java/package/service/dto/_AbstractAuditingDTO.java, generators/entity/index.js, package.json
Otherwise, DTO files were still checked & generated under `web/rest/dto` folder
=> Compatible with projects generated after 3.6.0 with DTOs moved to service folder

generators/app/index.js
Just a little upgrade of javers.
=> upgrade javers to latest version

README.md
=> correct travis urls in readme

generators/app/index.js
the second step to fix hipster-labs/generator-jhipster-entity-audit#49
merge only after first step jhipster/generator-jhipster#4916 is merged
fix hipster-labs/generator-jhipster-entity-audit#49
=> use renewed addElementToAdminMenu from main generator

generators/app/templates/src/main/java/package/domain/_EntityAuditEvent.java, generators/app/templates/src/main/resources/config/liquibase/changelog/_EntityAuditEvent.xml
fix hipster-labs/generator-jhipster-entity-audit#50
=> apply the same id field generation logic as in the main generator

generators/app/index.js, generators/app/templates/src/main/webapp/app/admin/entity-audit/_entity-audit.controller.js, generators/app/templates/src/main/webapp/app/admin/entity-audit/_entity-audit.detail.html, generators/app/templates/src/main/webapp/app/admin/entity-audit/_entity-audit.state.js, generators/app/templates/src/main/webapp/app/admin/entity-audit/_entity-audits.html, generators/app/templates/src/main/webapp/i18n/en/entity-audit.json, generators/app/templates/src/main/webapp/i18n/en/global.json, generators/app/templates/src/main/webapp/i18n/et/entity-audit.json, generators/app/templates/src/main/webapp/i18n/et/global.json
fix hipster-labs/generator-jhipster-entity-audit#15
=> add i18n support

generators/utils.js
Related to https://github.com/hipster-labs/generator-jhipster-entity-audit/issues/67
=> Fix entityTableName when it's defined in json

generators/app/templates/src/main/java/package/config/audit/_JaversAuthorProvider.java, travis/samples/gradle-ng1-mysql/.yo-rc.json
Just fixed this in my own project... - Resolves Issue #79
=> reflect changes in security to optionals v4.12.0+

generators/entity/index.js
=> New entity creation bugfix

generators/app/templates/src/main/webapp/i18n/pt-br/entity-audit.json, generators/app/templates/src/main/webapp/i18n/pt-br/global.json
Hi. I'm using this generator and I started to fix issues related to the new Angular version, but it seems that its already solved. So, as I did the internationalization for Portuguese (Brazil) anyway, I'm pushing it. 
Please let me know if you need more details.
Thanks.
=> Adding Portuguese (Brazil) files

generators/app/templates/src/main/java/package/web/rest/_JaversEntityAuditResource.java
This includes migration to micrometer and move of PaginationUtil to jhipster-framework
=> Fixes compatibility of Javers option with last JHipster version

generators/app/index.js, generators/app/templates/src/main/java/package/web/rest/_EntityAuditResource.java, generators/app/templates/src/main/java/package/web/rest/_JaversEntityAuditResource.java, generators/app/templates/src/main/webapp/angular/app/admin/entity-audit/_entity-audit-routing.module.ts, generators/app/templates/src/main/webapp/angular/app/admin/entity-audit/_entity-audit.module.ts, generators/utils.js, package.json
Updated the module to work with JHipster 6.x (tested with JHipster 6.4.1)
=> Updated the module to work with JHipster 6.x

generators/app/templates/src/main/java/package/web/rest/_EntityAuditResource.java
=> Use Spring @Transactional rather than javax @Transactional

generators/app/index.js, generators/generator-constants.js, generators/utils.js
Update Javers version and also make entity and its DTOs extend AbstractAuditingEntity and AbstractAuditingDTO for feature parity with custom audit
=> Improve javers

generators/app/index.js, package.json
=> Automatically register module as a dev dependency of the jhipster app

generators/app/templates/src/main/java/package/config/audit/_AsyncEntityAuditEventWriter.java
=> Fixed Typos

generators/app/templates/src/main/webapp/angular/app/admin/entity-audit/_entity-audit-modal.component.html
"string | undefined is not assignable to type 'string'" issue fixed in EntityAuditModalComponent
=> "string | undefined is not assignable to type 'string'" issue fixed

generators/app/index.js
Tested using current generator v6.10.4
=> Fix add jhipster-needle-add-admin-route

generators/java-audit/generator.mjs, generators/java-audit/templates/src/main/java/package/domain/_entity_.java.jhi.entity_audit.ejs, package-lock.json
Use multi-step template instead of regular expression to inject abstract entity audit.
And add jsdoc to test loading of auto complete definitions.
=> Use generic abstract entity and others improvements.

generators/java-audit/generator.mjs, generators/spring-boot-custom-audit/generator.mjs, generators/spring-boot-custom-audit/templates/src/main/java/package/audit/AsyncEntityAuditEventWriter.java.ejs, generators/spring-boot-custom-audit/templates/src/main/java/package/audit/EntityAuditEventListener.java.ejs, generators/spring-boot-custom-audit/templates/src/test/java/package/audit/TestEntityAuditEventWriter.java.ejs
I would like to propose some bugfixes for the issues
#184 TypeError: Cannot read properties of undefined (reading 'fields') with Jhipster 7.9.3
#185 Incorrect package names and imports in templates
#186 Duplicated code after regenerating application with entity-audit enabled
=> Fixes for #184, #185, #186

generators/angular-audit/templates/src/main/webapp/app/admin/entity-audit/entity-audit-modal.component.ts.ejs, generators/angular-audit/templates/src/main/webapp/app/admin/entity-audit/entity-audit.component.ts.ejs
Fix the issue #190 Audits is not showed when at least one action is DELETE
=> Fix issue 190

generators/spring-boot-custom-audit/templates/src/main/java/package/audit/AsyncEntityAuditEventWriter.java.ejs, generators/spring-boot-custom-audit/templates/src/main/java/package/audit/EntityAuditEventListener.java.ejs
This PR fixes some issues found with SonarQube. The rules were:
* Remove this unnecessary cast to "Object".
* Not enough arguments.
=> fix issues found with SonarQube

generators/java-audit/generator.js, generators/server/generator.js
fixes https://github.com/jhipster/generator-jhipster-entity-audit/issues/217.
=> fix null pointer

generators/angular-audit/resources/package.json
Reverts jhipster/generator-jhipster-entity-audit#237
=> Revert "Bump ngx-diff from 6.0.1 to 8.0.1 in /generators/angular-audit/resources"

generators/java-audit/__snapshots__/generator.spec.js.snap, generators/java-audit/command.js, generators/java-audit/generator.js, generators/java-audit/generator.spec.js
fixes https://github.com/jhipster/generator-jhipster-entity-audit/issues/291
=> fix prompt condition
